---
- name: Install Jenkins 
  hosts: all
  become: yes
  vars:
    ssh_use_pam: true # to allow access with our key on ec2
    jenkins_hostname: localhost

  roles:
    - role: geerlingguy.jenkins
    - role: geerlingguy.ansible-role-packer
    - role: geerlingguy.ansible
