---
- name: Install Jenkins 
  hosts: all
  become: yes
  vars:
    jenkins_hostname: localhost
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
  vars:
    ssh_use_pam: true # to allow access with our key on ec2
