---
- name: Install Jenkins 
  hosts: all
  become: yes
  vars:
    ssh_use_pam: true # to allow access with our key on ec2
    jenkins_hostname: localhost
    ansible_remote_tmp: /tmp/ansible
    jenkins_plugins: [ansicolor]

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.packer
    - geerlingguy.ansible
